name: Daily CMF Scan

on:
  schedule:
    # Runs at 9:00 UTC every weekday (Mon-Fri)
    - cron: '0 9 * * 1-5'
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-cmf-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # pip install numpy pandas scipy pyqtgraph
          pip install numpy pandas scipy

      - name: Run CMF scan script
        run: python scan_cmf_signals.py